### PR TITLE
Display User Events List

### PR DESCRIPTION
**Pull request by jchaing**
# Description

Allow user to easily find events that they're hosting or have RSVP'd to

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by jchaing** [comment]
[Display upcoming events to pizza eater dashboard](https://trello.com/c/UF2zv51S/29-display-upcoming-events-to-pizza-eater-dashboard)

**Comment by Jeffreyo3** [comment]
This component has come out very nicely. I'm looking forward to the sort-by implementation!

**Comment by agyin3** [comment]
really smart using a controller to render the component

**Comment by Jeffreyo3** [comment]
We will need to revisit later to deal with code climate.

**Pull request merged**
